name: deploy_to_firebase_hosting

# Define trigger point, on push on master branch, this workflow will be triggered.
on:
  push:
    branches: [ master ]

jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x' 
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.12.x'
        channel: 'beta'
    - name: Upgrades Flutter
      run: flutter upgrade
      working-directory: ./pomodoro
    - name: Enable Web
      run: flutter config --enable-web
      working-directory: ./pomodoro
    - name: Install Dependencies
      run: flutter packages get
      working-directory: ./pomodoro
    - name: Build Web
      run: flutter build web
      working-directory: ./pomodoro

  deploy_web:
    name: Deploy Web to Firebase Hosting
    needs: build_web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
